### ISSUE TITLE
banned mod

### ISSUE THREAD

**Issue by eksynn** [Phobos10/lilith_throne_mods#1]
how exactly do i unlock the magic abortion mod's zip file? i think i miss it, but i can't find any documentation on it at all.
moreover, where can the spell be acquired? can you get it from the buggy menu?

thanks in advance

**Comment by Phobos10** [comment]
On github, the mod is outside the archive.  This is an item.  Use on any of the NPCs.
For archive code: 001.

**Comment by Phobos10** [comment]
Close.

**Comment by Phobos10** [comment]
Test

**Comment by Phobos10** [comment]
Close
